### ISSUE TITLE
Added line breaks

### ISSUE THREAD

**Issue by eroock** [spookyuser/laconic_hover#20]
Since of late, the hover functions add a line break in the browser text. 
Demo: https://www.screenpresso.com/=Knzlb

**Comment by spookyuser** [comment]
Oh wow that's bad, thanks for alerting me. I think I know what's causing this should be fixed real soon :)

**Comment by spookyuser** [comment]
Hey @eroock just published an update that should fix this, let me know if it works for you. 
And thanks again for reporting this, can't believe I missed it 🤦‍♂️

**Comment by eroock** [comment]
Fix works. Thanks.
