### ISSUE TITLE
Does not handle redirects well

### ISSUE THREAD

**Issue by Bpendragon** [spookyuser/laconic_hover#34]
Title.

Steps to reporoduce:

1. Find a page where there is a link to a page that redirects to the main trope.
2. Hover over the link
3. Redirect is shown, but Laconic description is not. 

Example, this is from hovering over the link to [Omnipresent Trope](https://tvtropes.org/pmwiki/pmwiki.php/Main/OmnipresentTrope) (which redirects to Omnipresent Trope**s**) on the page [Spoilered Rotten](https://tvtropes.org/pmwiki/pmwiki.php/Main/SpoileredRotten)

![image](https://user-images.githubusercontent.com/5448822/204727380-b2ae4ece-65f6-4f5c-892d-366e9b80b772.png)

Suggested fix: if `Trope.title` contains 'aka: ' use anything ~~after~~ before this as the title when looking up the Laconic description

Edit: Fixed suggested fix, had the two halves swapped

**Comment by spookyuser** [comment]
Thanks for the bug report, i'll look into this asap!

**Comment by spookyuser** [comment]
Hey @Bpendragon  just to confirm what you'd like to see happen here ❤️

I don't see a laconic page for https://tvtropes.org/pmwiki/pmwiki.php/Main/OmnipresentTropes with or without the redirect, could you link me to where I could get the laconic from here please 😄 

Thanks so much again, this forced me to update the whole extension to typescript!

**Comment by spookyuser** [comment]
Sorrry it took so long!

I just fixed this :) will update now
![image](https://github.com/spookyuser/laconic_hover/assets/16196262/f7fa7d19-5e36-4291-bd1f-9fcd8b65ee13)
