### ISSUE TITLE
Invalid charset

### ISSUE THREAD

**Issue by amraymanaly** [spookyuser/laconic_hover#36]
On hovering over a link, it says "Loading..." but does nothing. On inspecting the console, it says invalid charset. It seems that the charset extracted from http headers is misleading for TextDecoder. Does hardcoding "UTF-8" fix it? Worked for me.

**Comment by spookyuser** [comment]
Thanks sm for the bug report! Will check this out!

**Comment by spookyuser** [comment]
Hey @amraymanaly i couldn't seem to replicate this, could you send me the url you saw this on?

**Comment by amraymanaly** [comment]
This happened on every page on every link. The charset JS detects in the headers is "ISO-8859-1" which TextDecoder says is invalid. Is it really just me? In any case, seems like a try...catch might be well. I'll pull...

**Comment by amraymanaly** [comment]
After some fiddling, I realize the problem was with another extension that blocked CORS requests. For some reason, that seemed to interfere with Laconic Hover. Not sure why though...

**Comment by spookyuser** [comment]
Wow so strange, thanks for the PR, that seems like a better way to handle it regardless :)
