### ISSUE TITLE
[path] is not a valid URL

### ISSUE THREAD

**Issue by SavannahJohnston** [spookyuser/laconic_hover#38]
Not sure why, but the extension is no longer working for me. Whenever I hover over a a link, instead of the laconic text it just shows me the URL path (e.g."/pmwiki/pmwiki.php/Main/Trope") followed by "is not a valid URL."

**Comment by spookyuser** [comment]
Thanks sm @SavannahJohnston <3 will check this out rn

**Comment by spookyuser** [comment]
Hey @SavannahJohnston just checking are you using firefox?

**Comment by SavannahJohnston** [comment]
Yes I am. Browser-specific issue eh? Darn.

**Comment by spookyuser** [comment]
Don't worry, it was super easy to fix, uploading the update to the store now, thanks for reporting this!

**Comment by SavannahJohnston** [comment]
Yay! Thank you! It works now!

**Comment by spookyuser** [comment]
Np!
